### ISSUE TITLE
list user not real-time

### ISSUE THREAD

**Issue by Tonnamkit** [Sitthata/14-sentences-backend#13]
![image](https://github.com/Sitthata/14-sentences-backend/assets/110712358/519f07fc-b9eb-403a-88ad-2815a63e40ad)

**Comment by LynchzDEV** [comment]
WOI

**Comment by Sitthata** [comment]
When Client 2 joins, the server likely notifies only Client 2 that it has joined the room. What you need to ensure is that when Client 2 (or any other client) joins the room, the server sends an update to all clients in that room.
```js
socket.on('joinLobby', (roomId, username) => {
  // Add user to the room
  // ...

  // Notify all clients in the room
  io.in(roomId).emit('roomInfo', updatedRoomUsers);
});
```

**Comment by LynchzDEV** [comment]
yeah yeah, its not working. maybe need more config at other place

WOI

**Comment by LynchzDEV** [comment]
DONE
